### ISSUE TITLE
Bug: I have problems with my Campfire Wallet 

### ISSUE THREAD

**Issue by hoube03** [firoorg/campfire#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've been having problems with my Campfire wallet for the past week. I mentioned it in the main group and one of the admins asked me to clear the Electrumx cache and reanalyze the blockchain, which I did, but nothing has been resolved: sometimes I see my balance, but sometimes I don't see it or my transaction history. What can I do?

### Expected Behavior

I wish everything would go back to normal 

### Reproduce Steps

Please help me solve this Issue 

### Environment

- Operating system and version:
- Device platform and version:
- Real device or emulator/simulator:

**Comment by nodesupport1** [comment]
@hoube03 Since clearing the Electrumx cache and reanalyzing the blockchain didn't fix the problem,I'll have to refer you to the official support live chat with the ticket ID CAM07638
Please see the link below to our dedicated support line:
[Campfire Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by justanwar** [comment]
Please try adding alternative Nodes. Connect to them, close the app fully, start the app again, clear electrumx cache and resync.

Electrumx02 should be the server closest to you, but you can try other servers as well.

Using mobile 4G connection might have the most issues. **Try with WiFi** as well if available. Also consider turning Tor on or off, or use VPN (if available).

The following nodes are available:
electrumx02.firo.org
electrumx01.firo.org
electrumx03.firo.org
electrumx.firo.org
(all port 50002)

**Comment by reubenyap** [comment]
Hi @hoube03 how was this resolved?
